/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeoManagerRouteImport } from './routes/geo-manager'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiModeRouteImport } from './routes/ai-mode'
import { Route as AeoManagerRouteImport } from './routes/aeo-manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResortsIndexRouteImport } from './routes/resorts.index'
import { Route as AiModeIndexRouteImport } from './routes/ai-mode.index'
import { Route as ResortsSlugRouteImport } from './routes/resorts.$slug'
import { Route as MicrositeSlugRouteImport } from './routes/microsite.$slug'
import { Route as GResortPageRouteImport } from './routes/g.$resort.$page'
import { Route as AiModeAgentsIdRouteImport } from './routes/ai-mode.agents.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoManagerRoute = GeoManagerRouteImport.update({
  id: '/geo-manager',
  path: '/geo-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModeRoute = AiModeRouteImport.update({
  id: '/ai-mode',
  path: '/ai-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoManagerRoute = AeoManagerRouteImport.update({
  id: '/aeo-manager',
  path: '/aeo-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortsIndexRoute = ResortsIndexRouteImport.update({
  id: '/resorts/',
  path: '/resorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModeIndexRoute = AiModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiModeRoute,
} as any)
const ResortsSlugRoute = ResortsSlugRouteImport.update({
  id: '/resorts/$slug',
  path: '/resorts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrositeSlugRoute = MicrositeSlugRouteImport.update({
  id: '/microsite/$slug',
  path: '/microsite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GResortPageRoute = GResortPageRouteImport.update({
  id: '/g/$resort/$page',
  path: '/g/$resort/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModeAgentsIdRoute = AiModeAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AiModeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aeo-manager': typeof AeoManagerRoute
  '/ai-mode': typeof AiModeRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/geo-manager': typeof GeoManagerRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/microsite/$slug': typeof MicrositeSlugRoute
  '/resorts/$slug': typeof ResortsSlugRoute
  '/ai-mode/': typeof AiModeIndexRoute
  '/resorts/': typeof ResortsIndexRoute
  '/ai-mode/agents/$id': typeof AiModeAgentsIdRoute
  '/g/$resort/$page': typeof GResortPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aeo-manager': typeof AeoManagerRoute
  '/analytics': typeof AnalyticsRoute
  '/geo-manager': typeof GeoManagerRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/microsite/$slug': typeof MicrositeSlugRoute
  '/resorts/$slug': typeof ResortsSlugRoute
  '/ai-mode': typeof AiModeIndexRoute
  '/resorts': typeof ResortsIndexRoute
  '/ai-mode/agents/$id': typeof AiModeAgentsIdRoute
  '/g/$resort/$page': typeof GResortPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aeo-manager': typeof AeoManagerRoute
  '/ai-mode': typeof AiModeRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/geo-manager': typeof GeoManagerRoute
  '/login': typeof LoginRoute
  '/pages': typeof PagesRoute
  '/review-queue': typeof ReviewQueueRoute
  '/settings': typeof SettingsRoute
  '/microsite/$slug': typeof MicrositeSlugRoute
  '/resorts/$slug': typeof ResortsSlugRoute
  '/ai-mode/': typeof AiModeIndexRoute
  '/resorts/': typeof ResortsIndexRoute
  '/ai-mode/agents/$id': typeof AiModeAgentsIdRoute
  '/g/$resort/$page': typeof GResortPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aeo-manager'
    | '/ai-mode'
    | '/analytics'
    | '/geo-manager'
    | '/login'
    | '/pages'
    | '/review-queue'
    | '/settings'
    | '/microsite/$slug'
    | '/resorts/$slug'
    | '/ai-mode/'
    | '/resorts/'
    | '/ai-mode/agents/$id'
    | '/g/$resort/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aeo-manager'
    | '/analytics'
    | '/geo-manager'
    | '/login'
    | '/pages'
    | '/review-queue'
    | '/settings'
    | '/microsite/$slug'
    | '/resorts/$slug'
    | '/ai-mode'
    | '/resorts'
    | '/ai-mode/agents/$id'
    | '/g/$resort/$page'
  id:
    | '__root__'
    | '/'
    | '/aeo-manager'
    | '/ai-mode'
    | '/analytics'
    | '/geo-manager'
    | '/login'
    | '/pages'
    | '/review-queue'
    | '/settings'
    | '/microsite/$slug'
    | '/resorts/$slug'
    | '/ai-mode/'
    | '/resorts/'
    | '/ai-mode/agents/$id'
    | '/g/$resort/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AeoManagerRoute: typeof AeoManagerRoute
  AiModeRoute: typeof AiModeRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  GeoManagerRoute: typeof GeoManagerRoute
  LoginRoute: typeof LoginRoute
  PagesRoute: typeof PagesRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  SettingsRoute: typeof SettingsRoute
  MicrositeSlugRoute: typeof MicrositeSlugRoute
  ResortsSlugRoute: typeof ResortsSlugRoute
  ResortsIndexRoute: typeof ResortsIndexRoute
  GResortPageRoute: typeof GResortPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-manager': {
      id: '/geo-manager'
      path: '/geo-manager'
      fullPath: '/geo-manager'
      preLoaderRoute: typeof GeoManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mode': {
      id: '/ai-mode'
      path: '/ai-mode'
      fullPath: '/ai-mode'
      preLoaderRoute: typeof AiModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-manager': {
      id: '/aeo-manager'
      path: '/aeo-manager'
      fullPath: '/aeo-manager'
      preLoaderRoute: typeof AeoManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resorts/': {
      id: '/resorts/'
      path: '/resorts'
      fullPath: '/resorts/'
      preLoaderRoute: typeof ResortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mode/': {
      id: '/ai-mode/'
      path: '/'
      fullPath: '/ai-mode/'
      preLoaderRoute: typeof AiModeIndexRouteImport
      parentRoute: typeof AiModeRoute
    }
    '/resorts/$slug': {
      id: '/resorts/$slug'
      path: '/resorts/$slug'
      fullPath: '/resorts/$slug'
      preLoaderRoute: typeof ResortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsite/$slug': {
      id: '/microsite/$slug'
      path: '/microsite/$slug'
      fullPath: '/microsite/$slug'
      preLoaderRoute: typeof MicrositeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$resort/$page': {
      id: '/g/$resort/$page'
      path: '/g/$resort/$page'
      fullPath: '/g/$resort/$page'
      preLoaderRoute: typeof GResortPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-mode/agents/$id': {
      id: '/ai-mode/agents/$id'
      path: '/agents/$id'
      fullPath: '/ai-mode/agents/$id'
      preLoaderRoute: typeof AiModeAgentsIdRouteImport
      parentRoute: typeof AiModeRoute
    }
  }
}

interface AiModeRouteChildren {
  AiModeIndexRoute: typeof AiModeIndexRoute
  AiModeAgentsIdRoute: typeof AiModeAgentsIdRoute
}

const AiModeRouteChildren: AiModeRouteChildren = {
  AiModeIndexRoute: AiModeIndexRoute,
  AiModeAgentsIdRoute: AiModeAgentsIdRoute,
}

const AiModeRouteWithChildren =
  AiModeRoute._addFileChildren(AiModeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AeoManagerRoute: AeoManagerRoute,
  AiModeRoute: AiModeRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  GeoManagerRoute: GeoManagerRoute,
  LoginRoute: LoginRoute,
  PagesRoute: PagesRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  SettingsRoute: SettingsRoute,
  MicrositeSlugRoute: MicrositeSlugRoute,
  ResortsSlugRoute: ResortsSlugRoute,
  ResortsIndexRoute: ResortsIndexRoute,
  GResortPageRoute: GResortPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
